spring.application.name=carrymate

# Server Configuration
server.port=${PORT:8080}

# Database Configuration
# Spring boot will automatically try to find the variables below from the OS/SystemEnvironment if defined.
spring.datasource.url=${DB_URL:jdbc:h2:mem:carrymate_db}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security Configuration
carrymate.jwt.secret=${JWT_SECRET:9a67475d459d49c6a1e9c8e1e1e1e1e1e1e1e1e1e1e1e1e1e1e1e1e1e1e1e1e1}
carrymate.jwt.expiration=${JWT_EXPIRATION:86400000}

# Logging
logging.level.org.springframework.security=DEBUG

# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_SUwWFcLuV8oRjZ}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:X2O4tgirwNufJoei48osVBVd}

# Email Config (Gmail)
spring.mail.host=${EMAIL_HOST:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME:shaikmirchimohammadrafi@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:ojsw ccny alku ihlv}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
